# Generated by Django 5.0.6 on 2024-07-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactrequest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
