# Generated by Django 5.0.6 on 2024-07-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contactrequest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(default='Your name', max_length=255),
        ),
    ]
