# Generated by Django 5.0.6 on 2024-07-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_remove_testimonial_email_testimonial_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
