# Generated by Django 5.0.6 on 2024-07-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0004_alter_testimonial_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='name',
        ),
    ]
